name: File-Thing PR CI
on:
  pull_request:
    branches:
      - "main"

env:
  CONAN_USER: automation
  CONAN_PASS: ${{ secrets.CONAN_PASS }}
  VERSION: 0.3

jobs:
  run_unit_tests:
    name: Build and run ft unit tests
    runs-on: self-hosted
    container:
      image: ubuntu:22.04
      ports:
        - 8082
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          apt update
          apt install -y build-essential cmake python3 python3-pip
      - name: Get Conan
        uses: turtlebrowser/get-conan@v1.2
      - name: Build and run unit tests
        run: |
          conan profile detect -f
          ./builder.sh unit_test
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "build/Release/test_detail.xml"
          show: "all"
        if: always()
  run_integration_tests:
    name: Build and run ft integration tests
    runs-on: self-hosted
    container:
      image: ubuntu:22.04
      ports:
        - 8082
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          apt update
          apt install -y build-essential cmake python3 python3-pip dh-make devscripts lintian
      - name: Get Conan
        uses: turtlebrowser/get-conan@v1.2
      - name: Build ft and run integration tests
        env:
          DEBEMAIL: "jason@example.com"
          DEBFULLNAME: "Jason Anderson"
        run: |
          ./builder.sh
          ./package.sh
          dpkg -i "ft_${VERSION}-1_amd64.deb"
          ./test_package.sh

